name: Sync Stable Version

on:
  push:
    branches:
      - main  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check version and Sync
        run: |
          
          VERSION=$(grep -oP 'vers\s*=\s*"\K[^"]+' optlib)
          
          echo "Version detected: $VERSION"

          
          if [[ ! "$VERSION" =~ "ex" ]]; then
            echo "Stable version! Syncing"
            cp optlib optlibS
            
            
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add optlibS
            git commit -m "Auto-sync stable version: $VERSION"
            git push
          else
            echo "Ex version ($VERSION). Waiting until a stable version"
          fi
